//
// File generated by rootcint at Sun May  8 00:16:02 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SnowflakeAppaDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SnowflakeAppaDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void Snowflake_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Snowflake_Dictionary();
   static void *new_Snowflake(void *p = 0);
   static void *newArray_Snowflake(Long_t size, void *p);
   static void delete_Snowflake(void *p);
   static void deleteArray_Snowflake(void *p);
   static void destruct_Snowflake(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Snowflake*)
   {
      ::Snowflake *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Snowflake),0);
      static ::ROOT::TGenericClassInfo 
         instance("Snowflake", "./Snowflake.hh", 10,
                  typeid(::Snowflake), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &Snowflake_Dictionary, isa_proxy, 0,
                  sizeof(::Snowflake) );
      instance.SetNew(&new_Snowflake);
      instance.SetNewArray(&newArray_Snowflake);
      instance.SetDelete(&delete_Snowflake);
      instance.SetDeleteArray(&deleteArray_Snowflake);
      instance.SetDestructor(&destruct_Snowflake);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Snowflake*)
   {
      return GenerateInitInstanceLocal((::Snowflake*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Snowflake*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Snowflake_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::Snowflake*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_Snowflake(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Snowflake : new ::Snowflake;
   }
   static void *newArray_Snowflake(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Snowflake[nElements] : new ::Snowflake[nElements];
   }
   // Wrapper around operator delete
   static void delete_Snowflake(void *p) {
      delete ((::Snowflake*)p);
   }
   static void deleteArray_Snowflake(void *p) {
      delete [] ((::Snowflake*)p);
   }
   static void destruct_Snowflake(void *p) {
      typedef ::Snowflake current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Snowflake

/********************************************************
* SnowflakeAppaDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSnowflakeAppaDict();

extern "C" void G__set_cpp_environmentSnowflakeAppaDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Snowflake.hh");
  G__cpp_reset_tagtableSnowflakeAppaDict();
}
#include <new>
extern "C" int G__cpp_dllrevSnowflakeAppaDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Snowflake */
static int G__SnowflakeAppaDict_296_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Snowflake* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Snowflake[n];
     } else {
       p = new((void*) gvp) Snowflake[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Snowflake;
     } else {
       p = new((void*) gvp) Snowflake;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->Draw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->Save((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->InitialTriangle((double) G__double(libp->para[0]), *((TVector2*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->GenerateFlake();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->CutUp((TLine*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->Analyze((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->Plots();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SnowflakeAppaDict_296_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Snowflake*) G__getstructoffset())->Area((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SnowflakeAppaDict_296_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Snowflake* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Snowflake(*(Snowflake*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Snowflake G__TSnowflake;
static int G__SnowflakeAppaDict_296_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Snowflake*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Snowflake*) (soff+(sizeof(Snowflake)*i)))->~G__TSnowflake();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Snowflake*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Snowflake*) (soff))->~G__TSnowflake();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SnowflakeAppaDict_296_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Snowflake* dest = (Snowflake*) G__getstructoffset();
   *dest = *(Snowflake*) libp->para[0].ref;
   const Snowflake& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Snowflake */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSnowflakeAppaDict {
 public:
  G__Sizep2memfuncSnowflakeAppaDict(): p(&G__Sizep2memfuncSnowflakeAppaDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSnowflakeAppaDict::*p)();
};

size_t G__get_sizep2memfuncSnowflakeAppaDict()
{
  G__Sizep2memfuncSnowflakeAppaDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSnowflakeAppaDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSnowflakeAppaDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLine*>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Snowflake */
static void G__setup_memvarSnowflake(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake));
   { Snowflake *p; p=(Snowflake*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"centerx=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"centery=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"mag=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"theta=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"deg2rad=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_TCanvas),-1,-1,4,"canvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"iters=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_TVector2),-1,-1,4,"x_hat=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_TVector2),-1,-1,4,"y_hat=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),G__defined_typename("vector<TLine*>"),-1,4,"lines=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),G__defined_typename("vector<TLine*>"),-1,4,"snowflake=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator),-1,-1,4,"vit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_TFile),-1,-1,4,"myfile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fIndex=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fPerimeter=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fArea=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fIndexArea=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fTotalArea=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"fNSides=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fSmallSide=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSnowflakeAppaDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSnowflake(void) {
   /* Snowflake */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake));
   G__memfunc_setup("Snowflake",938,G__SnowflakeAppaDict_296_0_1, 105, G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Draw",398,G__SnowflakeAppaDict_296_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Save",399,G__SnowflakeAppaDict_296_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitialTriangle",1536,G__SnowflakeAppaDict_296_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - - u 'TVector2' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateFlake",1294,G__SnowflakeAppaDict_296_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CutUp",497,G__SnowflakeAppaDict_296_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TLine' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Analyze",724,G__SnowflakeAppaDict_296_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Plots",530,G__SnowflakeAppaDict_296_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Area",377,G__SnowflakeAppaDict_296_0_9, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - - d - - 0 - - "
"i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Snowflake", 938, G__SnowflakeAppaDict_296_0_10, (int) ('i'), G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake), -1, 0, 1, 1, 1, 0, "u 'Snowflake' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Snowflake", 1064, G__SnowflakeAppaDict_296_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SnowflakeAppaDict_296_0_12, (int) ('u'), G__get_linked_tagnum(&G__SnowflakeAppaDictLN_Snowflake), -1, 1, 1, 1, 1, 0, "u 'Snowflake' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSnowflakeAppaDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSnowflakeAppaDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSnowflakeAppaDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_TLine = { "TLine" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_TVector2 = { "TVector2" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_Snowflake = { "Snowflake" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR = { "vector<TLine*,allocator<TLine*> >" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator = { "vector<TLine*,allocator<TLine*> >::iterator" , 99 , -1 };
G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLine*,allocator<TLine*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSnowflakeAppaDict() {
  G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_TCanvas.tagnum = -1 ;
  G__SnowflakeAppaDictLN_TLine.tagnum = -1 ;
  G__SnowflakeAppaDictLN_TVector2.tagnum = -1 ;
  G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_TFile.tagnum = -1 ;
  G__SnowflakeAppaDictLN_Snowflake.tagnum = -1 ;
  G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR.tagnum = -1 ;
  G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator.tagnum = -1 ;
  G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSnowflakeAppaDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_TLine);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_TVector2);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_TFile);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_Snowflake),sizeof(Snowflake),-1,1280,(char*)NULL,G__setup_memvarSnowflake,G__setup_memfuncSnowflake);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupSnowflakeAppaDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSnowflakeAppaDict()");
  G__set_cpp_environmentSnowflakeAppaDict();
  G__cpp_setup_tagtableSnowflakeAppaDict();

  G__cpp_setup_inheritanceSnowflakeAppaDict();

  G__cpp_setup_typetableSnowflakeAppaDict();

  G__cpp_setup_memvarSnowflakeAppaDict();

  G__cpp_setup_memfuncSnowflakeAppaDict();
  G__cpp_setup_globalSnowflakeAppaDict();
  G__cpp_setup_funcSnowflakeAppaDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSnowflakeAppaDict();
  return;
}
class G__cpp_setup_initSnowflakeAppaDict {
  public:
    G__cpp_setup_initSnowflakeAppaDict() { G__add_setup_func("SnowflakeAppaDict",(G__incsetup)(&G__cpp_setupSnowflakeAppaDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSnowflakeAppaDict() { G__remove_setup_func("SnowflakeAppaDict"); }
};
G__cpp_setup_initSnowflakeAppaDict G__cpp_setup_initializerSnowflakeAppaDict;

