/********************************************************************
* SnowflakeAppaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SnowflakeAppaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSnowflakeAppaDict();
extern void G__cpp_setup_inheritanceSnowflakeAppaDict();
extern void G__cpp_setup_typetableSnowflakeAppaDict();
extern void G__cpp_setup_memvarSnowflakeAppaDict();
extern void G__cpp_setup_globalSnowflakeAppaDict();
extern void G__cpp_setup_memfuncSnowflakeAppaDict();
extern void G__cpp_setup_funcSnowflakeAppaDict();
extern void G__set_cpp_environmentSnowflakeAppaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Snowflake.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SnowflakeAppaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_TCanvas;
extern G__linked_taginfo G__SnowflakeAppaDictLN_TLine;
extern G__linked_taginfo G__SnowflakeAppaDictLN_TVector2;
extern G__linked_taginfo G__SnowflakeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_TFile;
extern G__linked_taginfo G__SnowflakeAppaDictLN_Snowflake;
extern G__linked_taginfo G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR;
extern G__linked_taginfo G__SnowflakeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator;
extern G__linked_taginfo G__SnowflakeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
