//
// File generated by rootcint at Sun May  8 19:55:51 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TreeAppaDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TreeAppaDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void Tree_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Tree_Dictionary();
   static void *new_Tree(void *p = 0);
   static void *newArray_Tree(Long_t size, void *p);
   static void delete_Tree(void *p);
   static void deleteArray_Tree(void *p);
   static void destruct_Tree(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Tree*)
   {
      ::Tree *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Tree),0);
      static ::ROOT::TGenericClassInfo 
         instance("Tree", "./Tree.hh", 12,
                  typeid(::Tree), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &Tree_Dictionary, isa_proxy, 0,
                  sizeof(::Tree) );
      instance.SetNew(&new_Tree);
      instance.SetNewArray(&newArray_Tree);
      instance.SetDelete(&delete_Tree);
      instance.SetDeleteArray(&deleteArray_Tree);
      instance.SetDestructor(&destruct_Tree);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Tree*)
   {
      return GenerateInitInstanceLocal((::Tree*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Tree*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Tree_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::Tree*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_Tree(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Tree : new ::Tree;
   }
   static void *newArray_Tree(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Tree[nElements] : new ::Tree[nElements];
   }
   // Wrapper around operator delete
   static void delete_Tree(void *p) {
      delete ((::Tree*)p);
   }
   static void deleteArray_Tree(void *p) {
      delete [] ((::Tree*)p);
   }
   static void destruct_Tree(void *p) {
      typedef ::Tree current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Tree

/********************************************************
* TreeAppaDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTreeAppaDict();

extern "C" void G__set_cpp_environmentTreeAppaDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Tree.hh");
  G__cpp_reset_tagtableTreeAppaDict();
}
#include <new>
extern "C" int G__cpp_dllrevTreeAppaDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Tree */
static int G__TreeAppaDict_298_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Tree* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Tree[n];
     } else {
       p = new((void*) gvp) Tree[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Tree;
     } else {
       p = new((void*) gvp) Tree;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TreeAppaDictLN_Tree));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeAppaDict_298_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Tree*) G__getstructoffset())->Draw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeAppaDict_298_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Tree*) G__getstructoffset())->GenerateTree();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TreeAppaDict_298_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Tree* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Tree(*(Tree*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TreeAppaDictLN_Tree));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Tree G__TTree;
static int G__TreeAppaDict_298_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Tree*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Tree*) (soff+(sizeof(Tree)*i)))->~G__TTree();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Tree*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Tree*) (soff))->~G__TTree();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TreeAppaDict_298_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Tree* dest = (Tree*) G__getstructoffset();
   *dest = *(Tree*) libp->para[0].ref;
   const Tree& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Tree */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTreeAppaDict {
 public:
  G__Sizep2memfuncTreeAppaDict(): p(&G__Sizep2memfuncTreeAppaDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTreeAppaDict::*p)();
};

size_t G__get_sizep2memfuncTreeAppaDict()
{
  G__Sizep2memfuncTreeAppaDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTreeAppaDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTreeAppaDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLine*>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TreeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Tree */
static void G__setup_memvarTree(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TreeAppaDictLN_Tree));
   { Tree *p; p=(Tree*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"deg2rad=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fDisx=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fDisy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_TCanvas),-1,-1,4,"fCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fIter=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fLength=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_TVector2),-1,-1,4,"fOrigin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fOffsetY=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fTheta=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_TVector2),-1,-1,4,"yhat=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_TVector2),-1,-1,4,"xhat=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_TFile),-1,-1,4,"fFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator),-1,-1,4,"fVit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),G__defined_typename("vector<TLine*>"),-1,4,"fBranches=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),G__defined_typename("vector<TLine*>"),-1,4,"fStorage=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR),G__defined_typename("vector<TLine*>"),-1,4,"fTemp=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTreeAppaDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTree(void) {
   /* Tree */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TreeAppaDictLN_Tree));
   G__memfunc_setup("Tree",400,G__TreeAppaDict_298_0_1, 105, G__get_linked_tagnum(&G__TreeAppaDictLN_Tree), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Draw",398,G__TreeAppaDict_298_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateTree",1211,G__TreeAppaDict_298_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Tree", 400, G__TreeAppaDict_298_0_4, (int) ('i'), G__get_linked_tagnum(&G__TreeAppaDictLN_Tree), -1, 0, 1, 1, 1, 0, "u 'Tree' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Tree", 526, G__TreeAppaDict_298_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TreeAppaDict_298_0_6, (int) ('u'), G__get_linked_tagnum(&G__TreeAppaDictLN_Tree), -1, 1, 1, 1, 1, 0, "u 'Tree' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTreeAppaDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTreeAppaDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTreeAppaDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TreeAppaDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_TVector2 = { "TVector2" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_Tree = { "Tree" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR = { "vector<TLine*,allocator<TLine*> >" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator = { "vector<TLine*,allocator<TLine*> >::iterator" , 99 , -1 };
G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLine*,allocator<TLine*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTreeAppaDict() {
  G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TreeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TreeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TreeAppaDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__TreeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TreeAppaDictLN_TCanvas.tagnum = -1 ;
  G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TreeAppaDictLN_TFile.tagnum = -1 ;
  G__TreeAppaDictLN_TVector2.tagnum = -1 ;
  G__TreeAppaDictLN_Tree.tagnum = -1 ;
  G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR.tagnum = -1 ;
  G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator.tagnum = -1 ;
  G__TreeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTreeAppaDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_TVector2);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_Tree),sizeof(Tree),-1,1280,(char*)NULL,G__setup_memvarTree,G__setup_memfuncTree);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__TreeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupTreeAppaDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTreeAppaDict()");
  G__set_cpp_environmentTreeAppaDict();
  G__cpp_setup_tagtableTreeAppaDict();

  G__cpp_setup_inheritanceTreeAppaDict();

  G__cpp_setup_typetableTreeAppaDict();

  G__cpp_setup_memvarTreeAppaDict();

  G__cpp_setup_memfuncTreeAppaDict();
  G__cpp_setup_globalTreeAppaDict();
  G__cpp_setup_funcTreeAppaDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTreeAppaDict();
  return;
}
class G__cpp_setup_initTreeAppaDict {
  public:
    G__cpp_setup_initTreeAppaDict() { G__add_setup_func("TreeAppaDict",(G__incsetup)(&G__cpp_setupTreeAppaDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTreeAppaDict() { G__remove_setup_func("TreeAppaDict"); }
};
G__cpp_setup_initTreeAppaDict G__cpp_setup_initializerTreeAppaDict;

