/********************************************************************
* TreeAppaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TreeAppaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTreeAppaDict();
extern void G__cpp_setup_inheritanceTreeAppaDict();
extern void G__cpp_setup_typetableTreeAppaDict();
extern void G__cpp_setup_memvarTreeAppaDict();
extern void G__cpp_setup_globalTreeAppaDict();
extern void G__cpp_setup_memfuncTreeAppaDict();
extern void G__cpp_setup_funcTreeAppaDict();
extern void G__set_cpp_environmentTreeAppaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Tree.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TreeAppaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAppaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAppaDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TreeAppaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAppaDictLN_TCanvas;
extern G__linked_taginfo G__TreeAppaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TreeAppaDictLN_TFile;
extern G__linked_taginfo G__TreeAppaDictLN_TVector2;
extern G__linked_taginfo G__TreeAppaDictLN_Tree;
extern G__linked_taginfo G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgR;
extern G__linked_taginfo G__TreeAppaDictLN_vectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiterator;
extern G__linked_taginfo G__TreeAppaDictLN_reverse_iteratorlEvectorlETLinemUcOallocatorlETLinemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
